name: odin CI

on:
  push:
    branches:
      - master   # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - master   # Trigger the workflow on pull request targeting the 'master' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run the CI pipeline on the latest Ubuntu environment

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]  # Testing on multiple Python versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}  # Use the Python version from the matrix

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install the dependencies from the 'requirements.txt'

      - name: Install FastAPI and Uvicorn
        run: |
          pip install fastapi uvicorn  # Ensure FastAPI and Uvicorn are installed for testing

#      - name: Run tests with pytest
#        run: |
#          pytest --maxfail=1 --disable-warnings -q  # Run the tests with pytest and set options

#      - name: Upload test results
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-results
#          path: ./tests/results/  # Path where your test results are stored (adjust if necessary)

      - name: Check formatting with black
        run: |
          pip install black  # Install the black formatter
          black --check .  # Check code formatting (doesn't modify code)

      - name: Linting with flake8
        run: |
          pip install flake8  # Install flake8 for linting
          flake8 .  # Lint the repository code
